---
name: Bug Report
description: File a bug report for the project.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Which component has the problem?
      description: Select the affected component.
      options:
        - Frontend
        - Backend
        - Database
        - API
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug in detail.
    validations:
      required: true
---
**Describe the bug**
A clear and concise description of what the bug is.

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] 

**Additional context**
Add any other context about the problem here.